### ISSUE TITLE
Oracle Java 20

### ISSUE THREAD

**Issue by theronic** [zalky/cues#10]
```(:require [cues.queue :as q]))
nREPL server started on port 64179 on host localhost - nrepl://localhost:64179
(def q (q/queue ::my-queue))
Reflection warning, qbits/tape/tailer.clj:88:21 - call to static method sleep on java.lang.Thread can't be resolved (argument types: java.lang.Object).
Reflection warning, qbits/tape/tailer.clj:102:18 - call to static method sleep on java.lang.Thread can't be resolved (argument types: java.lang.Object).
=> nil
Execution error (NoSuchMethodException) at java.lang.Class/getDeclaredMethod (Class.java:2772).
sun.nio.ch.FileChannelImpl.unmap0(long,long)
(def a (q/appender q))
Execution error (AssertionError) at cues.queue/appender (queue.clj:211).
Assert failed: (queue? queue)
```

Same JVM opts as for Java 17. Same code and deps.edn works on Amazon Corretto Java 17.

**Comment by zalky** [comment]
Hi Petrus,

So as [mentioned in the installation notes](https://github.com/zalky/cues#installation-), Chronicle Queue only targets [Java LTS releases, which specifically means 8, 11, and 17](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc). The next LTS release they support will be 21.

There are reports that 18 works fine, but that 19 does not. I suspect therefore 20 will not either. You can read more about that [here](https://github.com/OpenHFT/Chronicle-Queue/issues/1286).

I'm sorry, I wish I had a more helpful answer for you :confused:. I will mark this as closed for now, barring any objections.
